apiVersion: v1
kind: Secret
metadata:
  name: smart-factory-secrets
  namespace: smart-factory
type: Opaque
data:
  # Base64 인코딩된 값들 (실제 배포시 교체 필요)
  # echo -n "user" | base64 => dXNlcg==
  # echo -n "password" | base64 => cGFzc3dvcmQ=
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: cHJlZGljdGl2ZV9tYWludGVuYW5jZQ==
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-factory-config
  namespace: smart-factory
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MQTT_BROKER_HOST: "mqtt"
  MQTT_BROKER_PORT: "1883"
  REDIS_URL: "redis://redis:6379"
  DEBUG: "false" 