# ConfigMap for smart factory application
# Secrets are dynamically created in GitHub Actions workflow
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-factory-config
  namespace: smart-factory
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MQTT_BROKER_HOST: "mqtt"
  MQTT_BROKER_PORT: "1883"
  REDIS_URL: "redis://redis:6379"
  DEBUG: "false" 
  DIRECT_TIMESCALE_WRITE: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smart-factory
data:
  APP_PROMETHEUS_PORT: "9090"
  APP_GRAFANA_PORT: "3000"
  # 프론트에서 iframe 임베드할 외부 접근 URL (예: GKE LoadBalancer IP 또는 Ingress 도메인)
  # 예시: http://34.64.xx.yy:3000 혹은 https://grafana.example.com
  APP_GRAFANA_EXTERNAL_URL: "http://localhost:3000"