# ConfigMap for smart factory application
# Secrets are dynamically created in GitHub Actions workflow
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-factory-config
  namespace: smart-factory
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MQTT_BROKER_HOST: "mqtt"
  MQTT_BROKER_PORT: "1883"
  REDIS_URL: "redis://redis:6379"
  DEBUG: "false" 
  DIRECT_TIMESCALE_WRITE: "false"