# ConfigMap for smart factory application
# Secrets are dynamically created in GitHub Actions workflow
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-factory-config
  namespace: smart-factory
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MQTT_BROKER_HOST: "mqtt"
  MQTT_BROKER_PORT: "1883"
  REDIS_URL: "redis://redis:6379"
  DEBUG: "false" 
  DIRECT_TIMESCALE_WRITE: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smart-factory
data:
  APP_PROMETHEUS_PORT: "9090"
  APP_GRAFANA_PORT: "3000"
  # 프론트에서 iframe 임베드할 외부 접근 URL (예: GKE LoadBalancer IP 또는 Ingress 도메인)
  # 예시: https://grafana.example.com (HTTPS 권장)
  APP_GRAFANA_EXTERNAL_URL: "http://localhost:3000"
  # 프론트가 호출할 백엔드 외부 접근 URL들 (도메인/HTTPS 적용 시 여기만 변경)
  # 예시: https://api.example.com/api/v1, wss://api.example.com/api/v1/ws
  APP_BACKEND_EXTERNAL_BASE_URL: "https://factorypdm.com/api/v1"
  APP_BACKEND_WS_URL: "wss://factorypdm.com/api/v1/ws"