name: Frontend CI

on:
  push:
    branches: ["main", "develop"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run lint
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Run Cypress
        run: npx cypress run || echo "Cypress tests require login and alert pages"
      - name: Check for Storybook
        id: check_storybook
        run: |
          if node -e "const p=require('./package.json'); process.exit(!(p.scripts && p.scripts['build-storybook']));"; then
            echo "storybook_exists=true" >> $GITHUB_OUTPUT
          else
            echo "storybook_exists=false" >> $GITHUB_OUTPUT
            echo 'Storybook script not found in package.json'
          fi
      - name: Build Storybook
        if: steps.check_storybook.outputs.storybook_exists == 'true'
        run: npm run build-storybook
      - name: Upload Storybook artifact
        if: steps.check_storybook.outputs.storybook_exists == 'true' && success()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: frontend/storybook-static
